### ISSUE TITLE
As a MLOps engineer, I would like to use a serving framework (e.g. OpenVINO, MLserver, etc.) so that I don't need to implement gRPC and REST services by myself (and other common functions)

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/ai-edge#1]
### TODO

- [x] #27

**Comment by israel-hdez** [comment]
For OpenVINO, I created the following gist: https://gist.github.com/israel-hdez/1848d5a9788140c6f2e42ce316c70d5b

On that gist, there is a Container file that can be built with `podman build -t ovms_face_detection -f Containerfile`. The resulting container will contain OpenVINO and a sample face-detection model built-in.

The container can be ran in the background with `podman run -d --rm -p 9000:9000 ovms_face_detection:latest`. It should become ready quickly.

In the same gist, there is a `test_inference.bash ` script. To test inference (which would prove that the container is working), you may run the script on an empty directory. Alternatively, you may run manually each statement in the script if you want to check what's happening. You will end up with a `results` directory that should contain an image with the results of the face detection. 

Feel free to add more images in the `images` directory and re-run inference to test some images of your liking.

**Comment by piotrpdev** [comment]
Stefan's code uses MLServer, see #16

**Comment by israel-hdez** [comment]
I finally was able to create a container using Stefan's models.

Here is the Containerfile to create the MLServer container for the `bike-share-auto-ml` model: https://gist.github.com/israel-hdez/1848d5a9788140c6f2e42ce316c70d5b#file-containerfile-mlserver-mlflow. You can change [L13](https://gist.github.com/israel-hdez/1848d5a9788140c6f2e42ce316c70d5b#file-containerfile-mlserver-mlflow-L13) to switch to the `bike-rentals-auto-ml` model and it still should work.

For building, invoke `podman build -f Containerfile.mlserver.mlflow -t mlserver-bikes-share`. For running, invoke `podman run --rm -p 9000:9000 -p 8080:8080 mlserver-bikes-share`.

The tricky part that give me headaches is that although the environment files have all needed python dependencies for the model to run, an additional dependency needs to be installed by invoking `pip install mlserver-mlflow` to let MLServer load the model correctly. I guess this is not included in the model dependencies by default, because it is specific to MLServer.

**Comment by israel-hdez** [comment]
We have an [example for OpenVINO](https://github.com/opendatahub-io/ai-edge/issues/1#issuecomment-1675398309) and an [example for MLServer](https://github.com/opendatahub-io/ai-edge/issues/1#issuecomment-1688911353).

There is an additional example for OpenVINO here: https://github.com/opendatahub-io/ai-edge/issues/2#issuecomment-1690298228.

Since we have examples for two serving runtimes, for the scope of a PoC I'll close this as done.

**Comment by devguyio** [comment]
I think for this to be done we need the actual manifests pushed in the repo, so I'm gonna reopen it to track that this is still missing and I think once #27 is done we can close this user story.
