### ISSUE TITLE
[BUG]: Open Data Hub isn't used anywhere

### ISSUE THREAD

**Issue by piotrpdev** [opendatahub-io/ai-edge#148]
### Describe the bug

As mentioned in https://github.com/opendatahub-io/ai-edge/pull/139#discussion_r1357806068, Open Data Hub isn't actually used anywhere in the PoC right now. Maybe #126 can fix this.

### To Reproduce

N/A

### Expected behavior

Open Data Hub is used for something.

### Screenshots (if applicable)

N/A

**Comment by adelton** [comment]
In https://github.com/opendatahub-io/ai-edge/pull/140 we propose the narrative

> If you wish to develop and train different models, Jupyter notebooks provided by Open Data Hub or Red Hat OpenShift Data Science can be used.

But I wouldn't necessarily consider the situation a Bug -- it just shows that the world has reasonably clear interfaces.

Frankly, I'd much rather focus on https://github.com/opendatahub-io/ai-edge/issues/136 than to artificially add use for Open Data Hub to the PoC.

**Comment by LaVLaS** [comment]
I agree that this is not a bug.  For demo purposes, we used an AzureML model as the starting point for the MLOps pipeline but other AI Edge use cases use ODH to show how a Data Scientist can build, train and push a model to S3 from within a Jupyter Notebook.  #126 & #136 proposes additional entry points using ODH for the AI Edge workflow

One of the outcomes of the initial work in this repo is to to provide an MLOps pipeline to users of ODH so that ODH is not just the entry point (Jupyter Notebook) to the workflow but also provide support for delivering the model to a remote environment from within the ODH experience

**Comment by piotrpdev** [comment]
Closing since this is not a bug.
