### ISSUE TITLE
As a MLOps engineer I would like to take a trained model and use an automated pipeline to package it inside a container so that it can be deployed to the near edge.

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/ai-edge#2]
We want to be able to show that ODH can train, build and push a model all within a single workflow.  We have a few options that are native to ODH: Data Science Pipelines, [Elyra](https://elyra.readthedocs.io/en/stable/) or access tekton directly.

### Sub Tasks
- [x] #16
- [x] #17
- [x] #18
- [x] #20
- [x] #27

**Comment by piotrpdev** [comment]
@stefan-bergstein [has already started work on this](https://github.com/stefan-bergstein/azureml-model-to-edge/tree/dev/tekton)

**Comment by devguyio** [comment]
@grdryn @israel-hdez are there still more work to do here? if you're folks are working on something it'd be great if you'd create a sub task for it. Thanks!

**Comment by LaVLaS** [comment]
@piotrpdev Thx for getting this working with tekton.  Can you start investigating the use of Elyra to execute that pipeline from a Jupyter notebook?  We want to make sure that the "AI' in AI at the Edge is fully supported by the ODH workflow

**Comment by piotrpdev** [comment]
@StevenTobin mentioned that it might be better to use a local model instead of downloading one from AzureML at least for now; useful in case there are network issues between the cluster and Azure. Stefan's code creates a PVC and downloads the model to it anyway so that ~~hopefully~~ shouldn't be hard to change.

**Comment by israel-hdez** [comment]
Related to this, I updated my OpenVino gist and added another Containerfile that uses an image for downloading from storage: https://gist.github.com/israel-hdez/1848d5a9788140c6f2e42ce316c70d5b#file-containerfile-with-storage-download.

It has both Azure and AwsS3, but you should use only one of them. You choose which one to use by modifying the `COPY` statement: https://gist.github.com/israel-hdez/1848d5a9788140c6f2e42ce316c70d5b#file-containerfile-with-storage-download-L32.

I've successfully tested that downloading from S3 works. About Azure, I don't have an account so I can't try it, but what is there should be what is needed.

The Containerfile is multi-staged. To port that to Tekton, I'd think we would need two tasks: one for downloading, and another one for building the containerized model; and both tasks would share some workspace so that the build Task can pick the downloaded model.

With that downloader-image, I'd expect that we can move away from using the Azure-specific Task in Stefan's pipeline.

**Comment by piotrpdev** [comment]
FYI both of Stefan's provided models use [`scikit-learn`](https://scikit-learn.org/stable/) which [doesn't seem to be directly supported by OpenVINO](https://docs.openvino.ai/2023.0/Supported_Model_Formats.html). If we want to we could convert it to [ONNX](https://onnx.ai/) using [`sklearn-onnx`](https://onnx.ai/sklearn-onnx/), or just use a different model.

**Comment by piotrpdev** [comment]
Continuing the above, we had a discussion in the team slack and decided to switch to an MLFlow + TensorFlow model for ease of use. TF is more popular and directly supported by OpenVINO (and MLFlow ofc). TensorFlow Lite is also commonly used on Edge devices (and is also supported by OpenVINO)

**Comment by israel-hdez** [comment]
Using this model: https://github.com/piotrpdev/azureml-model-to-edge/tree/dev/models/tensorflow-housing/mlflow-model.

For OpenVINO, assuming you have `cd`ed to the folder containing the model, the following script would serve the model:

```bash
# Copy model to a volume
podman volume create mlflow-tf-model
podman run -d --rm --name dummy -v mlflow-tf-model:/root alpine tail -f /dev/null
podman cp ./tf2model/. dummy:/root
podman exec -it dummy rm -f /root/fingerprint.pb
podman exec -it dummy chown -R 5000:5000  /root
podman stop dummy

# Run OpenVino with the model mounted
podman run -d --rm -p 9001:9001 --name openvino-model -v mlflow-tf-model:/models/1 docker.io/openvino/model_server:latest --model_path /models --model_name mlflow-tf-model --rest_port 9001 --shape auto
```

A sample infer request is the following:
```bash
# Infer request
curl -X POST http://localhost:9001/v1/models/mlflow-tf-model/versions/1:predict  -H "Content-Type: application/json" -d '{ "instances": [[8.3252, 41.0, 6.984127, 1.023810, 322.0, 2.555556, 37.88, -122.23]] }'
```

Expected infer response is: 
```json
{
   "predictions": [3.69443774]
}
```
